# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApConsultancy', '0004_remove_registeruser_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='job',
            field=models.CharField(choices=[(b'chevrolet', b'Chevrolet'), (b'mazda', b'Mazda'), (b'nissan', b'Nissan'), (b'toyota', b'Toyota'), (b'mitsubishi', b'Mitsubishi')], default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
