# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApConsultancy', '0005_registeruser_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='job',
            field=models.CharField(choices=[(b'Management', b'Management'), (b'Software', b'Software'), (b'BPO', b'BPO')], default=b'Select', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='registeruser',
            unique_together=set([('email', 'job')]),
        ),
    ]
